lib: [
  "_build/install/default/lib/basechar/.private/basechar__Basechar_custom.cmi" {".private/basechar__Basechar_custom.cmi"}
  "_build/install/default/lib/basechar/.private/basechar__Basechar_data.cmi" {".private/basechar__Basechar_data.cmi"}
  "_build/install/default/lib/basechar/META"
  "_build/install/default/lib/basechar/basechar.a"
  "_build/install/default/lib/basechar/basechar.cma"
  "_build/install/default/lib/basechar/basechar.cmi"
  "_build/install/default/lib/basechar/basechar.cmt"
  "_build/install/default/lib/basechar/basechar.cmti"
  "_build/install/default/lib/basechar/basechar.cmx"
  "_build/install/default/lib/basechar/basechar.cmxa"
  "_build/install/default/lib/basechar/basechar.cmxs"
  "_build/install/default/lib/basechar/basechar.ml"
  "_build/install/default/lib/basechar/basechar.mli"
  "_build/install/default/lib/basechar/basechar__.cmi"
  "_build/install/default/lib/basechar/basechar__.cmt"
  "_build/install/default/lib/basechar/basechar__.cmx"
  "_build/install/default/lib/basechar/basechar__.ml"
  "_build/install/default/lib/basechar/basechar__Basechar_custom.cmt"
  "_build/install/default/lib/basechar/basechar__Basechar_custom.cmx"
  "_build/install/default/lib/basechar/basechar__Basechar_data.cmt"
  "_build/install/default/lib/basechar/basechar__Basechar_data.cmx"
  "_build/install/default/lib/basechar/basechar_custom.ml"
  "_build/install/default/lib/basechar/basechar_data.ml"
  "_build/install/default/lib/basechar/dune-package"
  "_build/install/default/lib/basechar/opam"
]
doc: [
  "_build/install/default/doc/basechar/README.md"
]
